# Generated by Django 3.2.8 on 2021-11-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
