# Generated by Django 3.2.9 on 2021-11-16 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_product_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=150)),
                ('chat_id', models.CharField(max_length=50)),
                ('condition', models.CharField(default='off', max_length=5)),
                ('last_payment', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
