# Generated by Django 3.2.9 on 2021-11-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_tgusers_tguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='tguser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='chat_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='user_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
