# Generated by Django 3.2.9 on 2021-11-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211116_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='date_click',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='user_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
