# Generated by Django 3.2.9 on 2021-11-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211116_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='rbf',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='received',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='txid',
        ),
        migrations.AddField(
            model_name='invoice',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='uniq_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='invoice',
            name='username',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='invoice',
            name='wallet',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
